[workspace]
resolver = "2"
members = [
    "precepta-core", "precepta-lancedb",
    "precepta-mongodb", "precepta-neo4j",
    "precepta-qdrant", "precepta-core/precepta-core-derive",
    "precepta-sqlite"
]
