[workspace]
resolver = "2"
members = [
    "galactica-core", "galactica-lancedb",
    "galactica-mongodb", "galactica-neo4j",
    "galactica-qdrant", "galactica-core/galactica-core-derive",
    "galactica-sqlite"
]

