[tool.poetry]
name = "t5-base-cerebra-integration"
version = "0.0.1"
description = "t5 base integration with dannyglendale cerebra"
authors = ["Prajna"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
cerebra = "*"
requests = "^2.31.0"