[tool.poetry]
name = "t5-base-uagent-integration"
version = "0.0.1"
description = "t5 base integration with mostafakhaliid uagent"
authors = ["Prajna"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
vitruvia = "*"
requests = "^2.31.0"